# Generated by Django 4.1.5 on 2023-01-03 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funTrip', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questioin',
            new_name='Question',
        ),
    ]
